/*
 * JRegView.java
 *
 * Created on 11 September 2006, 21:26
 */
package org.darkstars.battlehub;

import java.awt.event.ActionListener;
import org.darkstars.battlehub.framework.CEvent;
import org.darkstars.battlehub.gui.CUISettings;
import org.darkstars.battlehub.CUserSettings;
import org.darkstars.battlehub.gui.CView;
import org.darkstars.battlehub.protocol.tasserver.CTASServerProtocol;
import javax.swing.SwingUtilities;
import org.darkstars.battlehub.framework.Misc;
import org.jvnet.lafwidget.LafWidget;
import org.jvnet.lafwidget.text.PasswordStrengthChecker;
import org.jvnet.lafwidget.utils.LafConstants.PasswordStrength;

/**
 *
 * @author  Shade
 */
public class JRegView extends CView implements  ActionListener {

    /** Creates new form JRegView
     * @param L 
     */
    public JRegView(LMain L) {
        LM = L;
        Initialize();
        ValidatePanel();
    }

    /**
     * 
     */
    @Override
    public void Initialize() {
        initComponents();
        setTitle("Reg");
        UserTitle = "Register";
    }

    /**
     * 
     */
    @Override
    public void ValidatePanel() {
        validate();
    //LM.DoValidate();
    }

    /**
     * 
     * @param e
     */
    @Override
    public void NewEvent(CEvent e) {
        if (e.IsEvent("REGISTRATIONACCEPTED")) {
            LMain.protocol.Disconnect();
            LMain.Registering = false;
            LMain.Toasts.AddMessage("Registration Complete! Please login with your new username and password.");
            if (LM.ViewExists("LoginPanel") == false) {
                CLoginPanel LP = new CLoginPanel(LM);
                LM.AddView(LP, true);
            } else {
                LM.SetFocus("LoginPanel");
            }
            LM.RemoveView(this);
        } else if (e.IsEvent("REGISTRATIONDENIED") == true) {
            LMain.protocol.Disconnect();
            LMain.Registering = false;
            LMain.Toasts.AddMessage("Registration Failed! Server says: " + Misc.makeSentence(e.data, 1));
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ServerCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Port = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Password2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        SHACheckBox = new javax.swing.JCheckBox();

        setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+8f));
        jLabel1.setText("Register");

        ServerCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "taspringmaster.clan-sy.com", "fnord.clan-sy.com", "compstomp.de", "localhost", "cheetah.sentvid.org" }));

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+6f));
        jLabel2.setText("Connection");

        jLabel3.setText("What server do you wish to register this username with?");

        Port.setText("8200");

        jLabel4.setFont(CUISettings.GetFont(12));
        jLabel4.setText("What port does this server use?");

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()+6f));
        jLabel5.setText("User data");

        Username.setNextFocusableComponent(Password);

        Password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 1, true));
        Password.setNextFocusableComponent(Password2);

        jLabel6.setText("What username would you like?");

        jLabel7.setText("And what password would you like?");

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getSize()+6f));
        jLabel8.setText("League & Ladder");
        jLabel8.setEnabled(false);

        jCheckBox1.setFont(CUISettings.GetFont(12));
        jCheckBox1.setText("Register me at the Spring ladder at spring-league.com");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setEnabled(false);
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton1.setFont(CUISettings.GetFont(12));
        jButton1.setText("Register");
        jButton1.addActionListener(this);

        jButton2.setFont(CUISettings.GetFont(12));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tango/16x16/actions/go-previous.png"))); // NOI18N
        jButton2.setText("back");
        jButton2.addActionListener(this);

        Password2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 1, true));

        jLabel9.setText("repeat your password again here:");

        SHACheckBox.setText("Use an SHA-1 password hash (advanced)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Port, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ServerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jCheckBox1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel9)))
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Password, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(Username, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(Password2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SHACheckBox)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ServerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel8)
                        .addGap(22, 22, 22)
                        .addComponent(jCheckBox1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Password2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SHACheckBox)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Password, Password2});

        Runnable doWorkRunnable = new Runnable() {

            public void run() {
                //
                Password.putClientProperty(LafWidget.PASSWORD_STRENGTH_CHECKER, new PasswordStrengthChecker() {

                    public PasswordStrength getStrength(char[] password) {
                        if (password == null)
                        return PasswordStrength.WEAK;
                        int length = password.length;
                        if (length < 3)
                        return PasswordStrength.WEAK;
                        if (length < 6)
                        return PasswordStrength.MEDIUM;
                        return PasswordStrength.STRONG;
                    }

                    public String getDescription(PasswordStrength strength) {
                        if (strength == PasswordStrength.WEAK)
                        return "<html>This password is <b>way</b> too weak</html>";
                        if (strength == PasswordStrength.MEDIUM)
                        return "<html>Come on, you can do<br> a little better than that</html>";
                        if (strength == PasswordStrength.STRONG)
                        return "OK";
                        return null;
                    }
                });
            }
        };
        SwingUtilities.invokeLater(doWorkRunnable);
        Runnable doWorkRunnable2 = new Runnable() {

            public void run() {
                //
                Password2.putClientProperty(LafWidget.PASSWORD_STRENGTH_CHECKER, new PasswordStrengthChecker() {

                    public PasswordStrength getStrength(char[] password) {
                        if (password == null)
                        return PasswordStrength.WEAK;
                        int length = password.length;
                        if (length < 3)
                        return PasswordStrength.WEAK;
                        if (length < 6)
                        return PasswordStrength.MEDIUM;
                        return PasswordStrength.STRONG;
                    }

                    public String getDescription(PasswordStrength strength) {
                        if (strength == PasswordStrength.WEAK)
                        return "<html>This password is <b>way</b> too weak</html>";
                        if (strength == PasswordStrength.MEDIUM)
                        return "<html>Come on, you can do<br> a little better than that</html>";
                        if (strength == PasswordStrength.STRONG)
                        return "OK";
                        return null;
                    }
                });
            }
        };
        SwingUtilities.invokeLater(doWorkRunnable2);
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == jButton2) {
            JRegView.this.jButton2ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton1) {
            JRegView.this.jButton1ActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    LMain.Registering = false;
    if (LM.ViewExists("LoginPanel") == false) {
        CLoginPanel LP = new CLoginPanel(LM);
        LM.AddView(LP, true);
    } else {
        LM.SetFocus("LoginPanel");
    }
    LM.RemoveView(this);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    LMain.Registering = true;
        String username = Username.getText().trim();
        if (username.equalsIgnoreCase("")) {
            LMain.Toasts.AddMessage("Type out your requested username");
            return;
        }
        String password = String.valueOf(Password.getPassword(), 0, Password.getPassword().length);
        String password2 = String.valueOf(Password2.getPassword(), 0, Password2.getPassword().length);
        if (!password2.equals(password)) {
            LMain.Toasts.AddMessage("error:: your passwords dont match, retype them out to be sure");
            return;
        }
        String protocol = "";//(String) protocolbox.getSelectedItem();

        CUserSettings.PutValue("lastprotocol", protocol);
        //if (protocol.equalsIgnoreCase("TASServer v0.33")) {
        LMain.protocol = new CTASServerProtocol();
        LMain.core.AddModule(LMain.protocol);
        LMain.protocol.Init(LM);
        LMain.protocol.Connect(ServerCombo.getSelectedItem().toString(), Integer.parseInt(Port.getText()));
        LMain.protocol.Register(username, password, SHACheckBox.isSelected());
}//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JPasswordField Password2;
    private javax.swing.JTextField Port;
    private javax.swing.JCheckBox SHACheckBox;
    private javax.swing.JComboBox ServerCombo;
    private javax.swing.JTextField Username;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
