/*
 * CChannelList.java
 *
 * Created on 18 June 2008, 12:56
 */
package org.darkstars.battlehub.gui;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import org.darkstars.battlehub.CChannelInfo;
import org.darkstars.battlehub.LMain;
import org.darkstars.battlehub.framework.protocol.IProtocol;
import org.jvnet.flamingo.common.ElementState;
import org.jvnet.flamingo.common.JCommandButton;
import org.jvnet.flamingo.common.JCommandButton.CommandButtonKind;
import org.jvnet.flamingo.common.JCommandButtonPanel;
import org.jvnet.flamingo.common.JIconPopupPanel;
import org.jvnet.flamingo.common.icon.ImageWrapperResizableIcon;
import org.jvnet.flamingo.common.icon.ResizableIcon;

/**
 *
 * @author  AF-Standard
 */
public class CChannelListing extends javax.swing.JPanel {

    JIconPopupPanel icons;
    JCommandButtonPanel panel;

    /** Creates new form CChannelList */
    public CChannelListing() {
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                BuildChannelsPanel();
            }
        });

        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                initComponents();
            }
        });
    }

    public void BuildChannelsPanel() {
        panel = new JCommandButtonPanel(ElementState.BIG);

        panel.addButtonGroup("Channels", 0);
        panel.addButtonGroup("Small Channels", 1);
        panel.addButtonGroup("Actions", 2);


        icons = new JIconPopupPanel(panel, 1, 0);
    }

    public static ResizableIcon GetChannelIcon(String channel) {
        ResizableIcon ri = null;
        String p = LMain.GetAbsoluteLobbyFolderPathStatic() + "images/channels/" + channel + ".png";
        File f = new File(p);
        if (f.canRead()) {
            try {
                URL url = f.toURI().toURL();
                ri = ImageWrapperResizableIcon.getIcon(url, new Dimension(64, 64));
            } catch (MalformedURLException ex) {
                Logger.getLogger(CChannelListing.class.getName()).log(Level.SEVERE, null, ex);
                URL url = CChannelListing.class.getResource("/images/tango/32x32/actions/tab-new.png");
                ri = ImageWrapperResizableIcon.getIcon(url, new Dimension(64, 64));
            }

        } else {
            URL url = CChannelListing.class.getResource("/images/tango/32x32/actions/tab-new.png");
            ri = ImageWrapperResizableIcon.getIcon(url, new Dimension(64, 64));
        }
        return ri;
    }

    public void AddChannel(final CChannelInfo channel, final IProtocol protocol) {
        //
        final ResizableIcon ri = GetChannelIcon(channel.getName());
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JCommandButton b = new JCommandButton(channel.getName(), ri);
                b.setCommandButtonKind(CommandButtonKind.ACTION_ONLY);
                b.setToolTipText("click to join #" + channel.getName());

                b.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        protocol.JoinChannel(channel.getName(), "");
                    }
                });

                if (channel.getUsercount() > 2) {
                    panel.addButtonToGroup("Channels", b);
                } else {
                    panel.addButtonToGroup("Small Channels", b);
                }
            }
        });
    }

    public void AddActionButton(final JCommandButton b) {
        //
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                panel.addButtonToGroup("Actions", b);
            }
        });
    }

    public void RemoveAllButtons() {
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                panel.removeAllGroups();
                panel.addButtonGroup("Channels", 0);
                panel.addButtonGroup("Small Channels", 1);
                panel.addButtonGroup("Actions", 2);
            }
        });



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        channelsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        channelsPanel.setLayout(new javax.swing.BoxLayout(channelsPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Channels");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(channelsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(channelsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        channelsPanel.add(icons);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel channelsPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
