/*
 * CContainerPanel.java
 *
 * Created on 13 June 2008, 15:49
 */

package org.darkstars.battlehub.gui;

import javax.swing.JComponent;
import javax.swing.SwingUtilities;

/**
 *
 * @author  AF-Standard
 */
public class CContainerPanel extends javax.swing.JPanel implements IGUIContainer{

    /** Creates new form CContainerPanel */
    public CContainerPanel() {
        SwingUtilities.invokeLater( new Runnable() {

            @Override
            public void run() {
                //
                initComponents();
            }
        });
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void SetGUIObject(final JComponent c) {
        System.out.println("added panel");
        SwingUtilities.invokeLater( new Runnable() {

            @Override
            public void run() {
                //
                removeAll();
                add(c);
                validate();
                repaint();
            }
        });
    }

    @Override
    public void RemoveGUIObjects() {
        SwingUtilities.invokeLater( new Runnable() {

            @Override
            public void run() {
                //
                removeAll();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
